class ConfigError(Exception): pass
class ModelLoadError(Exception): pass
class RetrievalError(Exception): pass
class RerankerError(Exception): pass
class RAGAnswerError(Exception): pass
class GuardrailViolation(Exception): pass
class SelfEvalFailure(Exception): pass
class ToolExecutionError(Exception): pass
class UnsafeSQLError(Exception): pass
class AgentExecutionError(Exception): pass
class ObservabilityError(Exception): pass
class ValidationError(Exception): pass
