from typing import List, Dict, Any, Optional
from src.llm_ops.core.schemas import GuardrailResult
from src.llm_ops.core.config import settings
from src.llm_ops.guardrails.prompt_injection_detector import check_prompt_injection
from src.llm_ops.guardrails.sql_guardrails import check_sql_safety
from src.llm_ops.core.logging import get_logger

logger = get_logger(__name__)

def check_input_guardrails(query: str, mode: str = "direct") -> GuardrailResult:
    if not settings.guardrail.guardrails_enabled:
        return GuardrailResult(passed=True, action_taken="allow")
        
    logger.debug(f"Checking input guardrails for mode: {mode}")
    
    # 1. Prompt Injection
    if settings.guardrail.block_prompt_injection:
        injection_result = check_prompt_injection(query)
        if not injection_result.passed:
            return injection_result
            
    # 2. SQL specific input guardrails
    if mode == "sql_debug":
        # In a real scenario we'd extract the SQL from the prompt to check here
        # For input guardrails on raw queries, we do a basic check
        sql_check = check_sql_safety(query)
        # Note: often the SQL is generated by the LLM (output), not just input
        # so this is just a pre-filter.
        if not sql_check.passed:
            return sql_check
            
    # 3. Credential leakage / production writes logic placeholder
    # ...
            
    return GuardrailResult(passed=True, action_taken="allow")
